### ISSUE TITLE
GetPartsFromPort Code Example:

### ISSUE THREAD

**Issue by mawesome4ever** [Hexcede/pilot.lua#1]
Link: https://github.com/Hexcede/pilot.lua/wiki/Microcontroller-Globals#array-getpartsfromportint-port-potentially-unfinished

Code:
```lua
local Switches = GetPartsFromPort(1, "Switch")
for _, Switch in ipairs(Switches) do
    Switch:Configure( { SwitchValue = true } )
end
```

**Comment by Hexcede** [comment]
Thanks! :smile:
I've added your code example and inserted some comments to explain each line. I have also matched the capitalization with the other few code examples I've added mainly just for consistency's sake.

https://github.com/Hexcede/pilot.lua/wiki/Microcontroller-Globals#array-getpartsfromportint-port-string-parttype-potentially-unfinished
