### ISSUE TITLE
Correcting issue with entry

### ISSUE THREAD

**Issue by hail12pink** [Hexcede/pilot.lua#4]
**Wiki page**: https://github.com/Hexcede/pilot.lua/wiki/Modem
**Name of entry**: :PostRequest(), :GetRequest()
* [ ] The entry is missing from the wiki
* [ ] The entry was deleted from `pilot.lua` but remains on the wiki
* [ ] The entry has been renamed or moved to another page
* [ ] The entry has incorrect return types
* [ ] The entry has incorrect arguments
* [x] The description is incorrect
**Correction**:
> How to correct the entry
the wiki says that it does not send a HTTP request or access the web, however this is false as it does send a HTTP request to autism's webserver

**Comment by mawesome4ever** [comment]
It doesn't access the real internet though, GET/POST is limited to a sandboxed "www"

**Comment by Hexcede** [comment]
I forgot to resolve this issue, but, I tweaked the wording slightly:
> This can't be used to access the web.
vs
> This does not emit an HTTP request or access the web.
