### ISSUE TITLE
Correcting issue with entry

### ISSUE THREAD

**Issue by hail12pink** [Hexcede/pilot.lua#6]
**Wiki page**: https://github.com/Hexcede/pilot.lua/wiki/Speaker
**Name of entry**:  function newindex
* [ ] The entry is missing from the wiki
* [ ] The entry was deleted from `pilot.lua` but remains on the wiki
* [ ] The entry has been renamed or moved to another page
* [ ] The entry has incorrect return types
* [ ] The entry has incorrect arguments
* [x] The description is incorrect
**Correction**:
> How to correct the entry
its clear that this is a typo when someone was trying to type __newindex for a metatable

**Comment by mawesome4ever** [comment]
Correct, very likely captured by the auto-scrip data compiler due to a metatable being used inside a method

**Comment by Hexcede** [comment]
Since its confirmed this is a bug and not an actual method I've removed the entry.
