### ISSUE TITLE
Keyboard.TextInputted Description is Inaccurate

### ISSUE THREAD

**Issue by hail12pink** [Hexcede/pilot.lua#7]
**Wiki page**: Keyboard
**Name of entry**: Keyboard.TextInputted
* [ ] Submit code example
* [ ] Deleted from `pilot.lua`
* [ ] Missing from wiki
* [ ] Renamed or moved
* [ ] Incorrect return types or arguments
* [x] The description is inaccurate
**Contribution**:
The current description is, "A Signal which fires when a Player writes a sentence on the Keyboard", which can be kind of misleading and might make people think it means a real sentence, imo it would make more sense to say something like, "A signal which fires when a player presses "enter" after typing something".

**Comment by Hexcede** [comment]
I'm not quite sure how this event works. I will assign @Weldify since they added the entry, but, I'm not sure what a proper description would be.

**Comment by Weldify** [comment]
done-ish
